#!/usr/bin/env bun
// SPDX-License-Identifier: MIT
//
// test-docs.ts — Automated documentation tests for SFFMC.
//
// Catches drift, broken links, em-dash regressions, version mismatches,
// AI tells, file path references, and similar documentation quality issues.
//
// Usage:
//   bun run scripts/test-docs.ts           # fast checks only
//   bun run scripts/test-docs.ts --live    # also run live CLI checks
//
// Exit code 0 = all checks pass, 1 = any check fails, 2 = internal error.

import {
  readFileSync,
  readdirSync,
  statSync,
  existsSync,
  mkdtempSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { join, relative, resolve, dirname } from "node:path"
import { tmpdir } from "node:os"
import { execSync } from "node:child_process"

// --------------------------------------------------------------------------
// Configuration
// --------------------------------------------------------------------------

const REPO_ROOT = resolve(import.meta.dir, "..")
const NPM_VERSION_EXPECTED = "0.16.1"
const README_LINE_LIMIT = 150

const AI_TELL_WORDS = [
  "seamlessly",
  "comprehensive",
  "robust",
  "leverage",
  "utilize",
  "facilitate",
  "furthermore",
  "moreover",
  "delve",
  "streamline",
  "holistic",
  "seamless",
  "cutting-edge",
  "state-of-the-art",
]

// Directories we never descend into when scanning for docs
// `dependencies/` holds cloned upstream sources (e.g. XiaomiMiMo/MiMo-Code)
// whose internal docs are not part of SFFMC's documentation surface.
const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  ".sffmc",
  ".slim",
  "state-archive",
  "coverage",
  ".next",
  "dependencies",
])

// CHANGELOG.md and CHANGELOG.ru.md are historical records: they intentionally
// reference packages, paths, and pre-decomposition file structures that no
// longer exist. Some checks (em-dash count, file-paths-in-docs, double-dash
// in titles) treat CHANGELOG as exempt so we don't have to rewrite history.
const HISTORICAL_DOCS = new Set([
  "CHANGELOG.md",
  "CHANGELOG.ru.md",
])

// Auto-generated docs (regenerated on demand) and internal skill templates.
// `codemap.md` is regenerated from the catemap.md script per AGENTS.md.
// Skill templates (packages/cognition/src/compose/skills/*.md) are
// per-task instructions; the words inside them are part of the skill's
// behavior, not user-facing documentation prose.
function isAutoGenerated(relPath: string): boolean {
  if (relPath === "codemap.md" || /\/codemap\.md$/.test(relPath)) return true
  if (relPath.startsWith("packages/cognition/src/compose/skills/")) return true
  if (relPath.startsWith("packages/safety/skills/")) return true
  return false
}

// --------------------------------------------------------------------------
// Types
// --------------------------------------------------------------------------

interface CheckResult {
  name: string
  status: "ok" | "warn" | "fail" | "skip"
  detail: string
}

// --------------------------------------------------------------------------
// Result bookkeeping
// --------------------------------------------------------------------------

const checks: CheckResult[] = []

function record(
  name: string,
  status: CheckResult["status"],
  detail: string,
): void {
  checks.push({ name, status, detail })
}

function formatStatus(status: CheckResult["status"]): string {
  switch (status) {
    case "ok":
      return "\x1b[32m✓\x1b[0m"
    case "warn":
      return "\x1b[33m!\x1b[0m"
    case "fail":
      return "\x1b[31m✗\x1b[0m"
    case "skip":
      return "\x1b[90m~\x1b[0m"
  }
}

// --------------------------------------------------------------------------
// Filesystem helpers
// --------------------------------------------------------------------------

function listMarkdownFiles(rootDir: string = REPO_ROOT): string[] {
  const out: string[] = []

  function walk(dir: string): void {
    let entries: string[]
    try {
      entries = readdirSync(dir)
    } catch {
      return
    }
    for (const entry of entries) {
      if (SKIP_DIRS.has(entry)) continue
      const full = join(dir, entry)
      let st
      try {
        st = statSync(full)
      } catch {
        continue
      }
      if (st.isDirectory()) {
        walk(full)
      } else if (st.isFile() && entry.toLowerCase().endsWith(".md")) {
        out.push(relative(REPO_ROOT, full))
      }
    }
  }

  walk(rootDir)
  return out.sort()
}

function readText(relPath: string): string {
  return readFileSync(join(REPO_ROOT, relPath), "utf8")
}

function countMatches(haystack: string, needle: RegExp): number {
  const matches = haystack.match(needle)
  return matches ? matches.length : 0
}

function safeExec(
  cmd: string,
  cwd: string = REPO_ROOT,
  env?: NodeJS.ProcessEnv,
): string {
  return execSync(cmd, {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    timeout: 30_000,
    env: env ?? process.env,
  })
}

// --------------------------------------------------------------------------
// Check 1 — em-dash detection
// --------------------------------------------------------------------------

function checkNoEmDash(): void {
  const files = listMarkdownFiles().filter(
    (f) => !HISTORICAL_DOCS.has(f) && !isAutoGenerated(f),
  )
  const offenders: Array<{ path: string; count: number }> = []
  let total = 0

  for (const f of files) {
    let text: string
    try {
      text = readText(f)
    } catch {
      continue
    }
    const n = countMatches(text, /—/g)
    if (n > 0) {
      offenders.push({ path: f, count: n })
      total += n
    }
  }

  if (total === 0) {
    record("no_em_dash", "ok", `0 em-dashes across ${files.length} files`)
    return
  }

  const sample = offenders
    .slice(0, 5)
    .map((o) => `${o.path}:${o.count}`)
    .join(", ")
  const more = offenders.length > 5 ? `, +${offenders.length - 5} more` : ""
  record(
    "no_em_dash",
    "fail",
    `${total} em-dashes in ${offenders.length} files — ${sample}${more}`,
  )
}

// --------------------------------------------------------------------------
// Check 2 — AI-tell vocabulary
// --------------------------------------------------------------------------

function checkNoAiTells(): void {
  const files = listMarkdownFiles().filter(
    (f) => !HISTORICAL_DOCS.has(f) && !isAutoGenerated(f),
  )
  const findings: Array<{ path: string; word: string }> = []

  const pattern = new RegExp(`\\b(${AI_TELL_WORDS.join("|")})\\b`, "gi")

  for (const f of files) {
    let text: string
    try {
      text = readText(f)
    } catch {
      continue
    }
    const matches = text.match(pattern)
    if (matches && matches.length > 0) {
      for (const m of matches) findings.push({ path: f, word: m.toLowerCase() })
    }
  }

  if (findings.length === 0) {
    record("no_ai_tells", "ok", `0 AI-style words across ${files.length} files`)
    return
  }
  const sample = findings
    .slice(0, 5)
    .map((f) => `${f.word}@${f.path}`)
    .join(", ")
  record(
    "no_ai_tells",
    "fail",
    `${findings.length} AI-tell hits — ${sample}${findings.length > 5 ? ", …" : ""}`,
  )
}

// --------------------------------------------------------------------------
// Check 3 — README size
// --------------------------------------------------------------------------

function checkReadmeSize(): void {
  const readme = "README.md"
  if (!existsSync(join(REPO_ROOT, readme))) {
    record("readme_size", "warn", "README.md missing")
    return
  }
  const lines = readText(readme).split("\n").length
  if (lines > README_LINE_LIMIT) {
    record(
      "readme_size",
      "warn",
      `${lines} lines (limit ${README_LINE_LIMIT}) — README is getting long`,
    )
    return
  }
  record("readme_size", "ok", `${lines} lines`)
}

// --------------------------------------------------------------------------
// Check 4 — stray console.log mentions in docs
// --------------------------------------------------------------------------

function checkNoConsoleLog(): void {
  // console.log mentions are often legitimate (PR template checklists, code
  // examples in fenced blocks, historical CHANGELOG references). We report
  // them as warn rather than fail and exclude CHANGELOG (historical).
  const files = listMarkdownFiles().filter((f) => !HISTORICAL_DOCS.has(f))
  const findings: Array<{ path: string; count: number }> = []

  for (const f of files) {
    let text: string
    try {
      text = readText(f)
    } catch {
      continue
    }
    const n = countMatches(text, /console\.log\b/g)
    if (n > 0) findings.push({ path: f, count: n })
  }

  if (findings.length === 0) {
    record("no_console_log", "ok", `0 console.log mentions in docs`)
    return
  }
  const sample = findings.map((o) => `${o.path}:${o.count}`).join(", ")
  record(
    "no_console_log",
    "warn",
    `${findings.length} file(s) mention console.log - ${sample} (likely PR template / code example)`,
  )
}

// --------------------------------------------------------------------------
// Check 5 — package version consistency
// --------------------------------------------------------------------------

function checkNpmVersionsConsistent(): void {
  const candidates = [
    "package.json",
    "packages/runtime/package.json",
    "packages/memory/package.json",
    "packages/cognition/package.json",
    "packages/safety/package.json",
    "packages/utilities/package.json",
  ]
  const drift: Array<{ path: string; got: string }> = []

  for (const rel of candidates) {
    const full = join(REPO_ROOT, rel)
    if (!existsSync(full)) {
      drift.push({ path: rel, got: "missing" })
      continue
    }
    let pkg: { version?: string }
    try {
      pkg = JSON.parse(readFileSync(full, "utf8"))
    } catch (e) {
      drift.push({ path: rel, got: `parse-error:${(e as Error).message}` })
      continue
    }
    const got = pkg.version ?? "(no version field)"
    if (got !== NPM_VERSION_EXPECTED) {
      drift.push({ path: rel, got })
    }
  }

  if (drift.length === 0) {
    record(
      "npm_versions_consistent",
      "ok",
      `${candidates.length} manifests all ${NPM_VERSION_EXPECTED}`,
    )
    return
  }
  const sample = drift
    .slice(0, 5)
    .map((d) => `${d.path}=${d.got}`)
    .join(", ")
  record(
    "npm_versions_consistent",
    "fail",
    `version drift — ${sample}${drift.length > 5 ? ", …" : ""}`,
  )
}

// --------------------------------------------------------------------------
// Check 6 — AI-style double-dash in headings
// --------------------------------------------------------------------------

function checkNoDoubleDashInTitles(): void {
  const files = listMarkdownFiles().filter(
    (f) => !HISTORICAL_DOCS.has(f) && !isAutoGenerated(f),
  )
  const findings: Array<{ path: string; line: number; heading: string }> = []

  for (const f of files) {
    let text: string
    try {
      text = readText(f)
    } catch {
      continue
    }
    const lines = text.split("\n")
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      const m = line.match(/^#{1,2}\s+(.+?)\s*$/)
      if (!m) continue
      const heading = m[1]
      // AI-tell: title contains " - " or " — " as a separator
      if (/(?:\s+—\s+|\s+-\s+)/.test(heading)) {
        findings.push({ path: f, line: i + 1, heading })
      }
    }
  }

  if (findings.length === 0) {
    record(
      "no_double_dash_in_titles",
      "ok",
      `no AI-style " - " or " — " in headings across ${files.length} files`,
    )
    return
  }
  const sample = findings
    .slice(0, 5)
    .map((f) => `${f.path}:${f.line}`)
    .join(", ")
  record(
    "no_double_dash_in_titles",
    "warn",
    `${findings.length} heading(s) with dash separator — ${sample}`,
  )
}

// --------------------------------------------------------------------------
// Check 7 — CHANGELOG currency
// --------------------------------------------------------------------------

function checkChangelogCurrency(): void {
  const rel = "CHANGELOG.md"
  if (!existsSync(join(REPO_ROOT, rel))) {
    record("changelog_currency", "fail", "CHANGELOG.md missing")
    return
  }
  const text = readText(rel)
  // Match a vX.Y.Z section header at line start (English CHANGELOG only)
  const escaped = NPM_VERSION_EXPECTED.replace(/\./g, "\\.")
  const re = new RegExp(`^##\\s+v${escaped}\\b`, "m")
  if (re.test(text)) {
    record(
      "changelog_currency",
      "ok",
      `CHANGELOG.md has ## v${NPM_VERSION_EXPECTED}`,
    )
    return
  }
  // Show the first heading we do see to aid debugging
  const first = text.match(/^##\s+v\S+/m)
  record(
    "changelog_currency",
    "fail",
    `CHANGELOG.md missing ## v${NPM_VERSION_EXPECTED}` +
      (first ? ` (found: ${first[0]})` : " (no v* headers at all)"),
  )
}

// --------------------------------------------------------------------------
// Check 8 — sffmc CLI sanity (live)
// --------------------------------------------------------------------------

function checkSffmcCli(live: boolean): void {
  if (!live) {
    record("sffmc_cli_works", "skip", "live check (pass --live to run)")
    return
  }
  const cli = join(REPO_ROOT, "bin", "sffmc")
  if (!existsSync(cli)) {
    record("sffmc_cli_works", "fail", `bin/sffmc missing at ${cli}`)
    return
  }

  let pathOut = ""
  let helpOut = ""
  let pathErr: string | null = null
  let helpErr: string | null = null

  try {
    pathOut = safeExec(`bash "${cli}" path`).trim()
  } catch (e) {
    pathErr = (e as Error).message
  }
  try {
    helpOut = safeExec(`bash "${cli}" help`).trim()
  } catch (e) {
    helpErr = (e as Error).message
  }

  const pathOk = !!pathOut && pathOut.endsWith("sffmc")
  const helpOk = helpOut.includes("init")

  if (pathOk && helpOk) {
    record(
      "sffmc_cli_works",
      "ok",
      `path=${pathOut}, help mentions 'init'`,
    )
    return
  }
  const parts: string[] = []
  if (!pathOk)
    parts.push(`path=${JSON.stringify(pathOut)}${pathErr ? ` (err: ${pathErr})` : ""}`)
  if (!helpOk) parts.push(`help-missing-init${helpErr ? ` (err: ${helpErr})` : ""}`)
  record("sffmc_cli_works", "fail", parts.join("; "))
}

// --------------------------------------------------------------------------
// Check 9 — sffmc init --all adds 5 plugins (live)
// --------------------------------------------------------------------------

function checkSffmcInitAll(live: boolean): void {
  if (!live) {
    record("sffmc_init_all_adds_5", "skip", "live check (pass --live to run)")
    return
  }
  const cli = join(REPO_ROOT, "bin", "sffmc")
  if (!existsSync(cli)) {
    record("sffmc_init_all_adds_5", "fail", `bin/sffmc missing`)
    return
  }

  // Create a private config dir so we never touch the user's real opencode.json
  const sandbox = mkdtempSync(join(tmpdir(), "sffmc-test-docs-"))
  const cfgDir = join(sandbox, "opencode")
  const cfgFile = join(cfgDir, "opencode.json")
  try {
    // Bun's runtime may not have jq; do a pre-check
    try {
      safeExec("command -v jq")
    } catch {
      record(
        "sffmc_init_all_adds_5",
        "fail",
        "jq not on PATH — required by sffmc init",
      )
      return
    }

    // Seed minimal config
    require("node:fs").mkdirSync(cfgDir, { recursive: true })
    writeFileSync(cfgFile, "{}\n", "utf8")

    let stdout = ""
    try {
      stdout = safeExec(`bash "${cli}" init --all --yes`, REPO_ROOT, {
        ...process.env,
        XDG_CONFIG_HOME: sandbox,
        HOME: sandbox,
        SFFMC_AUTO_YES: "1",
      })
    } catch (e) {
      const err = e as { stdout?: string; stderr?: string; message: string }
      stdout = (err.stdout ?? "") + (err.stderr ?? "")
      record(
        "sffmc_init_all_adds_5",
        "fail",
        `sffmc init failed: ${err.message}; output: ${stdout.slice(0, 400)}`,
      )
      return
    }

    // Count plugin entries
    const after = JSON.parse(readFileSync(cfgFile, "utf8")) as {
      plugin?: unknown[]
    }
    const plugins = Array.isArray(after.plugin) ? after.plugin : []
    const count = plugins.length

    if (count === 5) {
      record(
        "sffmc_init_all_adds_5",
        "ok",
        `init --all added 5 plugin entries to sandbox config`,
      )
      return
    }
    record(
      "sffmc_init_all_adds_5",
      "fail",
      `expected 5 plugin entries after init --all, got ${count}`,
    )
  } finally {
    try {
      rmSync(sandbox, { recursive: true, force: true })
    } catch {
      // best-effort cleanup
    }
  }
}

// --------------------------------------------------------------------------
// Check 10 — file paths referenced in docs exist
// --------------------------------------------------------------------------

function checkFilePathsInDocs(): void {
  const files = listMarkdownFiles()
  // Restrict scanning to the same docs we'd review as a maintainer.
  // CHANGELOG.md is intentionally exempt: it is a historical record that
  // references packages and paths that no longer exist post-decomposition.
  const targetSet = new Set([
    "README.md",
    "README.ru.md",
    "CONTRIBUTING.md",
    "RELEASE.md",
  ])
  for (const f of files) {
    if (f.startsWith("docs/") && f.endsWith(".md")) {
      targetSet.add(f)
    }
  }
  const targetFiles = files.filter((f) => targetSet.has(f)).sort()

  // Regex matches repo-relative paths that look like they should resolve.
  // We match anything starting with packages/, docs/, bin/, scripts/, config/,
  // .sffmc/, or AGENTS.md / CONTRIBUTING.md / LICENSE / README.md / CHANGELOG.md,
  // followed by an optional path tail.  Anchored to backticks, parens, or
  // whitespace so we avoid mid-URL false positives. The path tail stops at
  // a colon (used in TS named-export syntax like path:CONSTANT) or a file
  // extension boundary; identifiers after the path are stripped.
  const pathPattern =
    /(?:^|[`(\s>])((?:packages|docs|bin|scripts|config|\.sffmc)\/[^\s`()]*|AGENTS\.md|CONTRIBUTING\.md|RELEASE\.md|LICENSE|README\.md|CHANGELOG\.md)/gm

  const missing: Array<{ fromFile: string; referenced: string }> = []

  for (const f of targetFiles) {
    let text: string
    try {
      text = readText(f)
    } catch {
      continue
    }
    // Strip fenced code blocks to avoid false positives from example snippets
    const stripped = text.replace(/```[\s\S]*?```/g, "```\n```")
    let m: RegExpExecArray | null
    while ((m = pathPattern.exec(stripped)) !== null) {
      // Strip colon + identifier suffix (TS named-export syntax: path:CONST)
      // and trailing punctuation/whitespace
      const ref = m[1]
        .replace(/:[A-Za-z_$][\w$]*$/, "")
        .replace(/[).,;]+$/, "")
      // Skip URLs / HTTP refs and anything containing "://"
      if (ref.includes("://")) continue
      // Skip wildcard patterns
      if (ref.includes("*")) continue
      // Skip template placeholders like packages/<plugin>
      if (/<[a-z-]+>/i.test(ref)) continue
      // Skip fake "packages/foo" examples in composite-pattern docs
      if (/\/foo$/.test(ref)) continue
      // Skip upstream MiMo-Code packages documented in mimo-code-features.md
      if (f === "docs/mimo-code-features.md") continue
      const fullPath = join(REPO_ROOT, ref)
      if (!existsSync(fullPath)) {
        missing.push({ fromFile: f, referenced: ref })
      }
    }
  }

  if (missing.length === 0) {
    record(
      "file_paths_in_docs_exist",
      "ok",
      `0 missing paths across ${targetFiles.length} docs`,
    )
    return
  }
  const sample = missing
    .slice(0, 5)
    .map((m) => `${m.referenced} (in ${m.fromFile})`)
    .join("; ")
  record(
    "file_paths_in_docs_exist",
    "fail",
    `${missing.length} missing path(s) — ${sample}${missing.length > 5 ? "; …" : ""}`,
  )
}

// --------------------------------------------------------------------------
// Check 11 — github release link freshness
// --------------------------------------------------------------------------

function checkGithubReleaseLinkFresh(): void {
  const rel = "README.md"
  if (!existsSync(join(REPO_ROOT, rel))) {
    record("github_release_link_fresh", "skip", "README.md missing")
    return
  }
  const text = readText(rel)
  // Match pinned tag links: .../releases/tag/vX.Y.Z  (skip /releases/latest)
  const tagPattern =
    /https?:\/\/github\.com\/([^/\s]+)\/([^/\s]+)\/releases\/tag\/(v[0-9]+\.[0-9]+\.[0-9]+)/g
  const seen: Array<{ owner: string; repo: string; tag: string }> = []
  let m: RegExpExecArray | null
  while ((m = tagPattern.exec(text)) !== null) {
    seen.push({ owner: m[1], repo: m[2], tag: m[3] })
  }
  if (seen.length === 0) {
    record(
      "github_release_link_fresh",
      "ok",
      "no pinned release-tag links in README.md",
    )
    return
  }
  // Look for ones that point at this repo (Rahspide/sffmc) and are older
  // than NPM_VERSION_EXPECTED
  const ownLinks = seen.filter(
    (s) => s.owner === "Rahspide" && s.repo === "sffmc",
  )
  const stale = ownLinks.filter((s) => s.tag !== `v${NPM_VERSION_EXPECTED}`)
  if (stale.length === 0) {
    record(
      "github_release_link_fresh",
      "ok",
      `${ownLinks.length} own-repo release link(s) all current`,
    )
    return
  }
  const sample = stale.map((s) => s.tag).join(", ")
  record(
    "github_release_link_fresh",
    "warn",
    `stale release link(s) in README.md: ${sample} (current: v${NPM_VERSION_EXPECTED})`,
  )
}

// --------------------------------------------------------------------------
// Check 12 — packages/ directory count
// --------------------------------------------------------------------------

function checkPackageCount(): void {
  const dir = join(REPO_ROOT, "packages")
  if (!existsSync(dir)) {
    record("package_count_check", "fail", "packages/ missing")
    return
  }
  const entries = readdirSync(dir).filter((name) => {
    if (SKIP_DIRS.has(name)) return false
    const full = join(dir, name)
    try {
      return statSync(full).isDirectory()
    } catch {
      return false
    }
  })
  if (entries.length === 5) {
    record(
      "package_count_check",
      "ok",
      `5 packages: ${entries.sort().join(", ")}`,
    )
    return
  }
  record(
    "package_count_check",
    "fail",
    `expected 5 packages, found ${entries.length}: ${entries.sort().join(", ")}`,
  )
}

// --------------------------------------------------------------------------
// Runner
// --------------------------------------------------------------------------

function printTable(): void {
  const nameWidth = Math.max(
    ...checks.map((c) => c.name.length),
    "check".length,
  )
  console.log("")
  console.log("SFFMC doc tests:")
  console.log("")
  for (const c of checks) {
    const sym = formatStatus(c.status)
    const padded = c.name.padEnd(nameWidth, " ")
    console.log(`  ${sym} ${padded}  ${c.detail}`)
  }
  console.log("")

  const okN = checks.filter((c) => c.status === "ok").length
  const warnN = checks.filter((c) => c.status === "warn").length
  const failN = checks.filter((c) => c.status === "fail").length
  const skipN = checks.filter((c) => c.status === "skip").length
  console.log(
    `${checks.length} checks, ${okN} ok, ${warnN} warn, ${failN} fail${skipN > 0 ? `, ${skipN} skip` : ""}`,
  )
}

function main(): void {
  const live = process.argv.includes("--live")

  checkNoEmDash()
  checkNoAiTells()
  checkReadmeSize()
  checkNoConsoleLog()
  checkNpmVersionsConsistent()
  checkNoDoubleDashInTitles()
  checkChangelogCurrency()
  checkSffmcCli(live)
  checkSffmcInitAll(live)
  checkFilePathsInDocs()
  checkGithubReleaseLinkFresh()
  checkPackageCount()

  printTable()

  const failed = checks.filter((c) => c.status === "fail").length
  process.exit(failed > 0 ? 1 : 0)
}

main()